# Generated by Django 3.2.16 on 2023-09-15 12:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тэг публикации',
                'verbose_name_plural': 'Тэги публикаций',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, unique=True, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=30, unique=True, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=30, unique=True, verbose_name='Должность')),
                ('sociallinkname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Социальная сеть')),
                ('icon', models.CharField(blank=True, help_text='Необходим класс mdi', max_length=50, null=True, verbose_name='Иконка')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на социальную сеть')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Подробная информация')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainers.tag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
