# Generated by Django 3.2.16 on 2023-09-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_auto_20230915_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок вывода'),
        ),
    ]
