# Generated by Django 3.2.16 on 2023-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_trainer_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='position',
            field=models.CharField(max_length=30, verbose_name='Должность'),
        ),
    ]
