# Generated by Django 3.2.16 on 2023-10-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_alter_trainer_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.CharField(blank=True, choices=[('mdi-facebook', 'Facebook'), ('mdi-instagram', 'Instagram')], help_text='Необходим класс mdi', max_length=50, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='social',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='trainers.trainer', verbose_name='Пользователь'),
        ),
    ]
